/**
 * api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { ThirdPartyUserAccount } from './ThirdPartyUserAccount';
import { HttpFile } from '../http/http';

/**
* A user's KYC profile (they should only have one of these)
*/
export class KYCProfile {
    'id'?: string;
    'givenName'?: string;
    'familyName'?: string;
    'dateOfBirth'?: string;
    'socialSecurityNumber'?: string;
    'addresses'?: Array<Address>;
    'thirdPartyUserAccounts'?: Array<ThirdPartyUserAccount>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "givenName",
            "baseName": "givenName",
            "type": "string",
            "format": ""
        },
        {
            "name": "familyName",
            "baseName": "familyName",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateOfBirth",
            "baseName": "dateOfBirth",
            "type": "string",
            "format": ""
        },
        {
            "name": "socialSecurityNumber",
            "baseName": "socialSecurityNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<Address>",
            "format": ""
        },
        {
            "name": "thirdPartyUserAccounts",
            "baseName": "thirdPartyUserAccounts",
            "type": "Array<ThirdPartyUserAccount>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KYCProfile.attributeTypeMap;
    }
    
    public constructor() {
    }
}

