/**
 * api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* response
*/
export class OneTimePasscodeVerifyResponse {
    'jwt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jwt",
            "baseName": "jwt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OneTimePasscodeVerifyResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

