/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlaidAccount } from './PlaidAccount';
import { PlaidInstitution } from './PlaidInstitution';
import { HttpFile } from '../http/http';

/**
* request mirrors some elements of https://plaid.com/docs/link/web/#onsuccess
*/
export class PlaidConnectBankAccountsRequest {
    'plaidPublicToken'?: string;
    'institution'?: PlaidInstitution;
    'accounts'?: Array<PlaidAccount>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "plaidPublicToken",
            "baseName": "plaidPublicToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "institution",
            "baseName": "institution",
            "type": "PlaidInstitution",
            "format": ""
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<PlaidAccount>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlaidConnectBankAccountsRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

