/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type ProfileDataItemKind = "K_UNKNOWN" | "K_LEGAL_NAME" | "K_PHONE" | "K_EMAIL" | "K_ADDRESS" | "K_DATE_OF_BIRTH" | "K_US_SSN" | "K_US_GOVERNMENT_ID_DOC" | "K_PROOF_OF_ADDRESS_DOC" | "K_ACH_AUTHORIZATION_FORM_DOC" ;
