/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileDataItemInfo } from './ProfileDataItemInfo';
import { ThirdPartyUserAccount } from './ThirdPartyUserAccount';
import { HttpFile } from '../http/http';

/**
* represents all profile data for a user
*/
export class ProfileDataInfo {
    'profile'?: Array<ProfileDataItemInfo>;
    'wyre'?: ThirdPartyUserAccount;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "profile",
            "baseName": "profile",
            "type": "Array<ProfileDataItemInfo>",
            "format": ""
        },
        {
            "name": "wyre",
            "baseName": "wyre",
            "type": "ThirdPartyUserAccount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProfileDataInfo.attributeTypeMap;
    }
    
    public constructor() {
    }
}

