/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { DocumentInput } from './DocumentInput';
import { GovernmentIdDocumentInput } from './GovernmentIdDocumentInput';
import { HttpFile } from '../http/http';

/**
* request
*/
export class SaveProfileDataRequest {
    'legalName'?: string;
    'dateOfBirth'?: string;
    'ssn'?: string;
    'address'?: Address;
    'governmentIdDoc'?: GovernmentIdDocumentInput;
    'proofOfAddressDoc'?: DocumentInput;
    'achAuthorizationFormDoc'?: DocumentInput;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "legalName",
            "baseName": "legalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateOfBirth",
            "baseName": "dateOfBirth",
            "type": "string",
            "format": ""
        },
        {
            "name": "ssn",
            "baseName": "ssn",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Address",
            "format": ""
        },
        {
            "name": "governmentIdDoc",
            "baseName": "governmentIdDoc",
            "type": "GovernmentIdDocumentInput",
            "format": ""
        },
        {
            "name": "proofOfAddressDoc",
            "baseName": "proofOfAddressDoc",
            "type": "DocumentInput",
            "format": ""
        },
        {
            "name": "achAuthorizationFormDoc",
            "baseName": "achAuthorizationFormDoc",
            "type": "DocumentInput",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SaveProfileDataRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

