/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SnapWidgetProduct {
    'imageURL'?: string;
    'videoURL'?: string;
    'destinationAmount'?: number;
    'destinationTicker'?: string;
    'destinationAddress'?: string;
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "imageURL",
            "baseName": "imageURL",
            "type": "string",
            "format": ""
        },
        {
            "name": "videoURL",
            "baseName": "videoURL",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationAmount",
            "baseName": "destinationAmount",
            "type": "number",
            "format": "double"
        },
        {
            "name": "destinationTicker",
            "baseName": "destinationTicker",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationAddress",
            "baseName": "destinationAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnapWidgetProduct.attributeTypeMap;
    }
    
    public constructor() {
    }
}

