/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnapWidgetProduct } from './SnapWidgetProduct';
import { SnapWidgetWallet } from './SnapWidgetWallet';
import { HttpFile } from '../http/http';

export class SnapWidgetConfig {
    'appName'?: string;
    'wallets'?: Array<SnapWidgetWallet>;
    'intent'?: string;
    'focus'?: boolean;
    'theme'?: { [key: string]: string; };
    'product'?: SnapWidgetProduct;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appName",
            "baseName": "appName",
            "type": "string",
            "format": ""
        },
        {
            "name": "wallets",
            "baseName": "wallets",
            "type": "Array<SnapWidgetWallet>",
            "format": ""
        },
        {
            "name": "intent",
            "baseName": "intent",
            "type": "string",
            "format": ""
        },
        {
            "name": "focus",
            "baseName": "focus",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "theme",
            "baseName": "theme",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "SnapWidgetProduct",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnapWidgetConfig.attributeTypeMap;
    }
    
    public constructor() {
    }
}

