/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentMethod } from './PaymentMethod';
import { HttpFile } from '../http/http';

/**
* An object representing the user's account at a third party API
*/
export class ThirdPartyUserAccount {
    'id'?: string;
    'partnerId'?: string;
    'externalId'?: string;
    'credentialId'?: string;
    'status'?: string;
    'paymentMethods'?: Array<PaymentMethod>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "partnerId",
            "baseName": "partnerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalId",
            "baseName": "externalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentialId",
            "baseName": "credentialId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentMethods",
            "baseName": "paymentMethods",
            "type": "Array<PaymentMethod>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ThirdPartyUserAccount.attributeTypeMap;
    }
    
    public constructor() {
    }
}

