/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ThirdPartyUserAccountStatus } from './ThirdPartyUserAccountStatus';
import { UserAccountRemediation } from './UserAccountRemediation';
import { HttpFile } from '../http/http';

/**
* Represents the wyre user account status (or other tps)
*/
export class ThirdPartyUserAccount {
    'status'?: ThirdPartyUserAccountStatus;
    'vendorStatus'?: string;
    'remediations'?: Array<UserAccountRemediation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "ThirdPartyUserAccountStatus",
            "format": ""
        },
        {
            "name": "vendorStatus",
            "baseName": "vendorStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "remediations",
            "baseName": "remediations",
            "type": "Array<UserAccountRemediation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ThirdPartyUserAccount.attributeTypeMap;
    }
    
    public constructor() {
    }
}

