/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TokenMaterial } from './TokenMaterial';
import { HttpFile } from '../http/http';

export class TokenExchangeResponse {
    'tokens'?: TokenMaterial;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "TokenMaterial",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TokenExchangeResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

