/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* hints for the ui
*/
export class UserFlags {
    'hasPlaidItems'?: boolean;
    'hasWyreAccount'?: boolean;
    'hasWyrePaymentMethods'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasPlaidItems",
            "baseName": "hasPlaidItems",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasWyreAccount",
            "baseName": "hasWyreAccount",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasWyrePaymentMethods",
            "baseName": "hasWyrePaymentMethods",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserFlags.attributeTypeMap;
    }
    
    public constructor() {
    }
}

