/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from './User';
import { HttpFile } from '../http/http';

/**
* response
*/
export class UserDataResponse {
    'user'?: User;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserDataResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

