/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProfileDataItemKind } from './ProfileDataItemKind';
import { HttpFile } from '../http/http';

/**
* Represents an action that the client  must take in order to resolve a condition.
*/
export class UserAccountRemediation {
    'kind'?: ProfileDataItemKind;
    'description'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "ProfileDataItemKind",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserAccountRemediation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

