/**
 * api.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KYCProfile } from './KYCProfile';
import { Organization } from './Organization';
import { HttpFile } from '../http/http';

/**
* A user which is shared across customer applications
*/
export class User {
    'id'?: string;
    'email'?: string;
    'phone'?: string;
    'kycProfile'?: KYCProfile;
    'organizations'?: Array<Organization>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "kycProfile",
            "baseName": "kycProfile",
            "type": "KYCProfile",
            "format": ""
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<Organization>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
    
    public constructor() {
    }
}

