/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type UsGovernmentIdDocumentInputKind = "GI_UNKNOWN" | "GI_US_DRIVING_LICENSE" | "GI_US_PASSPORT_CARD" | "GI_US_GOVERNMENT_ID" | "GI_US_PASSPORT" ;
