/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UsGovernmentIdDocumentInputKind } from './UsGovernmentIdDocumentInputKind';
import { HttpFile } from '../http/http';

export class UsGovernmentIdDocumentInput {
    'kind'?: UsGovernmentIdDocumentInputKind;
    'fileIds'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "UsGovernmentIdDocumentInputKind",
            "format": ""
        },
        {
            "name": "fileIds",
            "baseName": "fileIds",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsGovernmentIdDocumentInput.attributeTypeMap;
    }
    
    public constructor() {
    }
}

