/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from './User';
import { UserFlags } from './UserFlags';
import { HttpFile } from '../http/http';

/**
* response
*/
export class ViewerDataResponse {
    'user'?: User;
    'flags'?: UserFlags;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "UserFlags",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ViewerDataResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

