/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WyrePaymentMethod } from './WyrePaymentMethod';
import { HttpFile } from '../http/http';

export class WyrePaymentMethods {
    'paymentMethods'?: Array<WyrePaymentMethod>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentMethods",
            "baseName": "paymentMethods",
            "type": "Array<WyrePaymentMethod>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WyrePaymentMethods.attributeTypeMap;
    }
    
    public constructor() {
    }
}

