/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WyreCreateDebitCardOrderResponse {
    'reservation'?: string;
    'orderId'?: string;
    'status'?: string;
    'transferId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reservation",
            "baseName": "reservation",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "transferId",
            "baseName": "transferId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WyreCreateDebitCardOrderResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

