/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { HttpFile } from '../http/http';

/**
* response
*/
export class WyreCreateAccountRequest {
    'individualLegalName'?: string;
    'individualResidenceAddress'?: Address;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "individualLegalName",
            "baseName": "individualLegalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "individualResidenceAddress",
            "baseName": "individualResidenceAddress",
            "type": "Address",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WyreCreateAccountRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

