/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WyreTransfer } from './WyreTransfer';
import { HttpFile } from '../http/http';

export class WyreTransfers {
    'transfers'?: Array<WyreTransfer>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "transfers",
            "baseName": "transfers",
            "type": "Array<WyreTransfer>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WyreTransfers.attributeTypeMap;
    }
    
    public constructor() {
    }
}

