/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WyreGetDebitCardOrderAuthorizationsResponse {
    'walletOrderId'?: string;
    'smsNeeded'?: boolean;
    'card2faNeeded'?: boolean;
    'authorization3dsUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "walletOrderId",
            "baseName": "walletOrderId",
            "type": "string",
            "format": ""
        },
        {
            "name": "smsNeeded",
            "baseName": "smsNeeded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "card2faNeeded",
            "baseName": "card2faNeeded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "authorization3dsUrl",
            "baseName": "authorization3dsUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WyreGetDebitCardOrderAuthorizationsResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

