/**
 * Flux API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: evergreen
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WyreDebitCardInfo } from './WyreDebitCardInfo';
import { HttpFile } from '../http/http';

export class WyreConfirmDebitCardQuoteRequest {
    'card'?: WyreDebitCardInfo;
    'dest'?: string;
    'sourceCurrency'?: string;
    'destCurrency'?: string;
    'sourceAmount'?: number;
    'reservationId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "card",
            "baseName": "card",
            "type": "WyreDebitCardInfo",
            "format": ""
        },
        {
            "name": "dest",
            "baseName": "dest",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceCurrency",
            "baseName": "sourceCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "destCurrency",
            "baseName": "destCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceAmount",
            "baseName": "sourceAmount",
            "type": "number",
            "format": "double"
        },
        {
            "name": "reservationId",
            "baseName": "reservationId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WyreConfirmDebitCardQuoteRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

