version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "saturday"
    target-branch: "dev"
    labels:
      - "npm dependencies"
