name: InstallNodeJS
description: Install NodeJS
inputs:
  NODE_VERSION:
    description: nodejs version to install
    required: true
runs:
  using: composite
  steps:
    # https://github.com/nodejs/help/wiki/Installation
    - name: Install NodeJS
      shell: bash
      run: |
        pushd /tmp
        curl -O https://nodejs.org/dist/v${{ inputs.NODE_VERSION }}/node-v${{ inputs.NODE_VERSION }}-linux-x64.tar.xz
        popd

        sudo tar -xJf /tmp/node-v${{ inputs.NODE_VERSION }}-linux-x64.tar.xz -C /usr/local/lib
        echo 'export PATH=/usr/local/lib/node-v${{ inputs.NODE_VERSION }}-linux-x64/bin:$PATH' >> ~/.bash_profile
