name: InstallNodeJS
description: Install NodeJS
inputs:
  NODE_VERSION:
    description: nodejs version to install
    required: true
runs:
  using: composite
  steps:
    - name: Install NodeJS
      shell: bash
      run: |
        nvm install ${{ inputs.NODE_VERSION }}
        nvm use ${{ inputs.NODE_VERSION }}
