// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/khoerling/flux/api/lib/integrations/firestore"
	"github.com/khoerling/flux/api/lib/integrations/sendgrid"
	"github.com/khoerling/flux/api/lib/integrations/wyre"
	"github.com/khoerling/flux/api/lib/server"
)

// Injectors from wire.go:

// InitializeServer creates the main server container
func InitializeServer() (server.Server, error) {
	sendAPIKey, err := sendgrid.ProvideSendClientAPIKey()
	if err != nil {
		return server.Server{}, err
	}
	client := sendgrid.ProvideSendClient(sendAPIKey)
	fireProjectID, err := firestore.ProvideFirestoreProjectID()
	if err != nil {
		return server.Server{}, err
	}
	firestoreClient, err := firestore.ProvideFirestore(fireProjectID)
	if err != nil {
		return server.Server{}, err
	}
	wyreClient := wyre.NewClient()
	serverServer := server.ProvideServer(client, firestoreClient, wyreClient)
	return serverServer, nil
}
