// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/khoerling/flux/api/lib/auth"
	"github.com/khoerling/flux/api/lib/db"
	"github.com/khoerling/flux/api/lib/integrations/firestore"
	"github.com/khoerling/flux/api/lib/integrations/plaid"
	"github.com/khoerling/flux/api/lib/integrations/sendgrid"
	"github.com/khoerling/flux/api/lib/integrations/wyre"
	"github.com/khoerling/flux/api/lib/server"
	plaid2 "github.com/plaid/plaid-go/plaid"
)

// Injectors from wire.go:

// InitializeServer creates the main server container
func InitializeServer() (server.Server, error) {
	sendAPIKey, err := sendgrid.ProvideSendClientAPIKey()
	if err != nil {
		return server.Server{}, err
	}
	client := sendgrid.ProvideSendClient(sendAPIKey)
	fireProjectID, err := firestore.ProvideFirestoreProjectID()
	if err != nil {
		return server.Server{}, err
	}
	firestoreClient, err := firestore.ProvideFirestore(fireProjectID)
	if err != nil {
		return server.Server{}, err
	}
	config, err := wyre.ProvideWyreConfig()
	if err != nil {
		return server.Server{}, err
	}
	wyreClient := wyre.NewClient(config)
	clientOptions, err := plaid.ProvideClientOptions()
	if err != nil {
		return server.Server{}, err
	}
	plaidClient, err := plaid2.NewClient(clientOptions)
	if err != nil {
		return server.Server{}, err
	}
	privateKey, err := auth.ProvideJwtPrivateKey()
	if err != nil {
		return server.Server{}, err
	}
	jwtSigner := auth.JwtSigner{
		PrivateKey: privateKey,
	}
	publicKey := auth.ProvideJwtPublicKey(privateKey)
	jwtVerifier := auth.JwtVerifier{
		PublicKey: publicKey,
	}
	dbDb := db.Db{
		Firestore: firestoreClient,
	}
	serverServer := server.ProvideServer(client, firestoreClient, wyreClient, plaidClient, jwtSigner, jwtVerifier, dbDb)
	return serverServer, nil
}
