// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/khoerling/flux/api/lib/integrations/firestore"
	"github.com/khoerling/flux/api/lib/integrations/sendgrid"
	"github.com/khoerling/flux/api/lib/server"
)

// Injectors from wire.go:

// InitializeServer creates the main server container
func InitializeServer() server.Server {
	sendAPIKey := sendgrid.ProvideSendClientAPIKey()
	client := sendgrid.ProvideSendClient(sendAPIKey)
	fireProjectID := firestore.ProvideFirestoreProjectID()
	firestoreClient := firestore.ProvideFirestore(fireProjectID)
	serverServer := server.ProvideServer(client, firestoreClient)
	return serverServer
}
