name: DeployWeb
description: Deploy the web tree
inputs:
  GCP_SA_KEY:
    description: service account key
    required: true
  GCP_PROJECT_ID:
    description: gcp project id
    required: true
  BUILD_SCRIPT:
    description: script to use
    required: true
  API_BASE_URL:
    description: api base url to use
    required: true
  WIDGET_URL:
    description: widget url to use
    required: true
  DEBUG:
    description: debug settings to use
    required: true
  WYRE_BASE_URL:
    description: the wyre base URL for retrieving Plaid config
    required: true  
  INIT_API_BASE_URL:
    description: todo
    required: true
runs:
  using: composite
  steps:
    - name: Deploy Web Tree
      shell: bash
      run: |
        node -v
        npm -v
        ${{ inputs.BUILD_SCRIPT }}

        pushd /tmp
        echo -n ${{ inputs.GCP_SA_KEY }} | base64 --decode > gcloud-service-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud-service-key.json"
        popd

        npx firebase-tools -P ${{ inputs.GCP_PROJECT_ID }} -c firebase.deploy.json deploy --only hosting
      env:
        # Init API base URL is typically only needed for the dev env
        INIT_API_BASE_URL: ${{ inputs.INIT_API_BASE_URL }} 
        API_BASE_URL: ${{ inputs.API_BASE_URL }}
        WIDGET_URL: ${{ inputs.WIDGET_URL }}
        WYRE_BASE_URL: ${{ inputs.WYRE_BASE_URL }}
        DEBUG: ${{ inputs.DEBUG }}
