// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/khoerling/flux/api/lib/db/firebase_db"
	"github.com/khoerling/flux/api/lib/encryption"
	"github.com/khoerling/flux/api/lib/integration_t_manager"
	"github.com/khoerling/flux/api/lib/integrations/firestore"
)

// Injectors from wire.go:

func InitializeTestManager() (integration_t_manager.Manager, error) {
	fireProjectID, err := firestore.ProvideFirestoreProjectID()
	if err != nil {
		return integration_t_manager.Manager{}, err
	}
	client, err := firestore.ProvideFirestore(fireProjectID)
	if err != nil {
		return integration_t_manager.Manager{}, err
	}
	config, err := encryption.ProvideConfig()
	if err != nil {
		return integration_t_manager.Manager{}, err
	}
	manager, err := encryption.NewManager(config)
	if err != nil {
		return integration_t_manager.Manager{}, err
	}
	db := firebase_db.Db{
		Firestore:         client,
		EncryptionManager: manager,
	}
	integration_t_managerManager := integration_t_manager.Manager{
		Db: db,
	}
	return integration_t_managerManager, nil
}
