// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/khoerling/flux/api/lib/db"
	"github.com/khoerling/flux/api/lib/encryption"
	"github.com/khoerling/flux/api/lib/integration_test"
	"github.com/khoerling/flux/api/lib/integrations/firestore"
)

// Injectors from wire.go:

func InitializeTestManager() (integration_test.Manager, error) {
	fireProjectID, err := firestore.ProvideFirestoreProjectID()
	if err != nil {
		return integration_test.Manager{}, err
	}
	client, err := firestore.ProvideFirestore(fireProjectID)
	if err != nil {
		return integration_test.Manager{}, err
	}
	config, err := encryption.ProvideConfig()
	if err != nil {
		return integration_test.Manager{}, err
	}
	manager, err := encryption.NewManager(config)
	if err != nil {
		return integration_test.Manager{}, err
	}
	dbDb := &db.Db{
		Firestore:         client,
		EncryptionManager: manager,
	}
	integration_testManager := integration_test.Manager{
		Db: dbDb,
	}
	return integration_testManager, nil
}
