name: Build & Push GCR API Image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/api-docker.yml'
      - 'api/**'
      - '!api/README.md'

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCP_SA_KEY }}
          registry: gcr.io
          project_id: silken-phalanx-305703
          image_name: snap-api
          image_tag: ${{ github.sha }}
          context: ./api
          dockerfile: ./api/Dockerfile