name: Ensure Dockerfile builds when changed (will push in future)

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/api-docker.yml
      - api/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#        with:
#          driver-opts: network=host
      -
        name: Test Dockerfile Build
        uses: docker/build-push-action@v2
        with:
          context: api
          push: false
