name: API Build & Deploy

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'
      - '!api/README.md'

jobs:
  test: 
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          curl -O  https://storage.googleapis.com/firebase-preview-drop/emulator/cloud-firestore-emulator-v1.11.7.jar
          java -jar cloud-firestore-emulator-v1.11.7.jar &
          sleep 2

          . .env.ci
          make test
        working-directory: api
  deploy-jobrunner: 
    needs: test
    name: Build/Deploy JobRunner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy RunSnapJob Cloud Function
        run: |
          pushd /tmp

          echo -n "$GCP_SA_KEY" | base64 --decode > gcloud-service-key.json

          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
          tar -xzf google-cloud-sdk-332.0.0-linux-x86_64.tar.gz

          ./google-cloud-sdk/install.sh --usage-reporting false
          gcloud auth activate-service-account --key-file gcloud-service-key.json

          popd

          bin/get-snap-env-secret --project silken-phalanx-305703 > snap-env
          bin/env2yaml snap-env > snap-env-yaml

          bin/deploy-jobrunner --project silken-phalanx-305703 --env-vars-file snap-env-yaml
        working-directory: api
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-api:
    needs: test
    name: Build/Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build/Push Docker Image to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCP_SA_KEY }}
          registry: gcr.io
          project_id: silken-phalanx-305703
          image_name: snap-api
          image_tag: ${{ github.sha }}
          context: ./api
          dockerfile: ./api/Dockerfile
      - name: Deploy RunSnapJob Cloud Function
        run: |
          pushd /tmp

          echo -n "$GCP_SA_KEY" | base64 --decode > gcloud-service-key.json

          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
          tar -xzf google-cloud-sdk-332.0.0-linux-x86_64.tar.gz

          ./google-cloud-sdk/install.sh --usage-reporting false
          gcloud auth activate-service-account --key-file gcloud-service-key.json

          popd

          bin/get-snap-env-secret --project silken-phalanx-305703 > snap-env
          bin/env2knative snap-env snap-api gcr.io/silken-phalanx-305703/snap-api:${{ github.sha }} > snap-env-knative
          cat snap-knative

          bin/deploy-api --project silken-phalanx-305703 snap-knative
        working-directory: api
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}