name: API Build & Deploy

on:
  push:
    branches:
      - master
      - dev
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'
      - '!api/README.md'

jobs:
  test: 
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          curl -O  https://storage.googleapis.com/firebase-preview-drop/emulator/cloud-firestore-emulator-v1.11.7.jar
          java -jar cloud-firestore-emulator-v1.11.7.jar &
          sleep 2

          . .env.ci
          make test
        working-directory: api
  build-api:
    name: "Build/Push Docker Image"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCP_SA_KEY }}
          registry: gcr.io
          project_id: silken-phalanx-305703
          image_name: snap-api
          image_tag: ${{ github.sha }}
          context: ./api
          dockerfile: ./api/Dockerfile
  deploy-development-api:
    name: "[D] Deploy API"
    needs: build-api
    runs-on: ubuntu-latest
    if: github.ref == refs/heads/dev
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-api
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT_ID: silken-phalanx-305703
          CONTAINER_REPO: gcr.io/silken-phalanx-305703/snap-api
  deploy-development-jobrunner: 
    name: "[D] Build/Deploy JobRunner"
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == refs/heads/dev
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-snap-job
        with:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} 
          GCP_PROJECT_ID: silken-phalanx-305703
  deploy-sandbox-api:
    name: "[S] Deploy API"
    needs: build-api
    runs-on: ubuntu-latest
    if: github.ref == refs/heads/master
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-api
        with:
          GCP_SA_KEY: ${{ secrets.SANDBOX_GCP_SA_KEY }}
          GCP_PROJECT_ID: ds-snap-sandbox
          CONTAINER_REPO: gcr.io/silken-phalanx-305703/snap-api
  deploy-sandbox-jobrunner: 
    needs: test
    name: "[S] Build/Deploy JobRunner"
    runs-on: ubuntu-latest
    if: github.ref == refs/heads/master
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-snap-job
        with:
          GCP_SA_KEY: ${{ secrets.SANDBOX_GCP_SA_KEY }} 
          GCP_PROJECT_ID: ds-snap-sandbox

