name: API Build & Deploy

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'
      - '!api/README.md'

jobs:
  #test: 
  deploy-jobrunner: 
    #needs: test
    name: Build/Deploy JobRunner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy RunSnapJob Cloud Function
        run: |
          echo -n "$GCP_SA_KEY" | base64 --decode > /tmp/gcloud-service-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud-service-key.json"

          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-332.0.0-linux-x86_64.tar.gz
          tar -xzf google-cloud-sdk-332.0.0-linux-x86_64.tar.gz

          ./google-cloud-sdk/install.sh --usage-reporting false
          gcloud init

          bin/deploy-jobrunner --project silken-phalanx-305703
        working-directory: api
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
       #credentials: ${{ secrets.GCP_SA_KEY }}
  # build-and-push-to-gcr:
  #   #needs: test
  #   name: Build/Deploy API
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build/Push Docker Image to GCR
  #       uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
  #       with:
  #         gcloud_service_key: ${{ secrets.GCP_SA_KEY }}
  #         registry: gcr.io
  #         project_id: silken-phalanx-305703
  #         image_name: snap-api
  #         image_tag: ${{ github.sha }}
  #         context: ./api
  #         dockerfile: ./api/Dockerfile
  #     - name: Deploy Docker Image to CloudRun
  #       uses: google-github-actions/deploy-cloudrun@main
  #       with:
  #         image: gcr.io/silken-phalanx-305703/snap-api:${{ github.sha }}
  #         service: snap-api
  #         credentials: ${{ secrets.GCP_SA_KEY }}