name: Web Build & Deploy

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/web.yml'
      - 'firebase.json'
      - 'widget/**'
      - 'docs/**'
      - 'web/**'
      - 'api/lib/swagger/swagger-ui.html'
      - 'api/client/**'
      - 'bin/build-web'

jobs:
  deploy-web: 
    name: Build/Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy Firebase Hosting Web Tree
        run: |
          bin/build-web

          pushd /tmp
          echo -n "$GCP_SA_KEY" | base64 --decode > gcloud-service-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud-service-key.json"
          popd

          npx firebase-tools -c firebase.deploy.json deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          API_BASE_URL: https://api.snapwallet.io
          WIDGET_URL: https://snapwallet.io/widget
          DEBUG: 'SnapWallet:error,SnapWallet:warn,SnapWallet:info'
