name: Web Build & Deploy

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/web.yml'
      - 'firebase.json'
      - 'widget/**'
      - 'init/**'
      - 'docs/**'
      - 'web/**'
      - 'api/lib/swagger/swagger-ui.html'
      - 'api/client/**'
      - 'bin/build-web'

jobs:
  deploy-development-web: 
    name: "[D] Build/Deploy Web"
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-web
        with:
          GCP_PROJECT_ID: silken-phalanx-305703
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          BUILD_SCRIPT: bin/build-web
          API_BASE_URL: https://api.snapwallet.io
          WIDGET_URL: https://snapwallet.io/widget
          # TODO: remove SnapWallet:debug ?
          DEBUG: 'SnapWallet:error,SnapWallet:warn,SnapWallet:info,SnapWallet:debug'
  deploy-sandbox-web: 
    name: "[S] Build/Deploy Web"
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-web
        with:
          GCP_PROJECT_ID: ds-snap-sandbox
          GCP_SA_KEY: ${{ secrets.SANDBOX_GCP_SA_KEY}}
          BUILD_SCRIPT: bin/build-sandbox-web
          API_BASE_URL: https://sandbox-api.snapwallet.io
          WIDGET_URL: https://sandbox.snapwallet.io/widget
          DEBUG: 'SnapWallet:error,SnapWallet:warn,SnapWallet:info,SnapWallet:debug'