name: Web Build & Deploy

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/web.yml'
      - 'widget/**'
      - 'docs/**'
      - 'api/lib/swagger/swagger-ui.html'

jobs:
  deploy-web: 
    name: Build/Deploy Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy Firebase Hosting Web Tree
        run: |
          pushd /tmp
          echo -n "$GCP_SA_KEY" | base64 --decode > gcloud-service-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud-service-key.json"
          popd
          curl https://firebase.tools/bin/linux/latest -o firebase

          bin/build-web

          ./firebase deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}